language: ruby
cache: bundler
rvm:
  - 2.1.2
bundler_args: --without development
env: DATABASE_URL=postgres://127.0.0.1:5432/transferatu_test
before_script:
  - createdb transferatu_test
script: bundle exec rspec
notifications:
  email: true
services:
  - redis-server
addons:
  postgresql: "9.3"
